baseURL = "https://hkyeong0703.github.io"
languageCode = "en-us"
title = "hkyeong's blog"
theme = "uBlogger"
enableEmoji = true
enableRobotsTXT = true

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[parmas]
title = "hkyeong's blog"
author = "HyeonKyeong Kim"
description = "#developer #devops #backend"
profilePicture = "images/profile.jpeg"
copyright = "2020-2021"
CommentoURL = "https://commento.example.com/js/commento.js"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/hkyeong0703/"
